### ISSUE TITLE
Occasional error if an actor is deleted for a token that still exists on the scene

### ISSUE THREAD

**Issue by etriebe** [theripper93/Combat-Booster#10]
When closing an actor sheet, I occasionally see the following error. 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
[Detected 1 package: combatbooster]
    at CombatBooster.js:24:54
    at Array.find (<anonymous>)
    at CombatBooster.js:24:34
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10216:13)
    at foundry.js:10155:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:10155:33)
    at ClientDatabaseBackend._updateDocuments (foundry.js:10036:17)
    at async Function.updateDocuments (document.mjs:373:21)
    at async Actor5e.update (document.mjs:456:21)
    at async Tidy5eNPC._onSubmit (foundry.js:3822:7)
    at async Tidy5eNPC.submit (foundry.js:4105:5)
    at async Tidy5eNPC.close (foundry.js:4077:19)
    at async Tidy5eNPC.close (foundry.js:4189:5)
```

I think updating combatbooster.js - line 24 to the following will fix it. 

```js
      : canvas.tokens.placeables.find((t) => !t && t.actor.id == actor.id)
```

**Comment by theripper93** [comment]
fixed
