### ISSUE TITLE
Bug: Syntax error, unrecognized expression: HP: 17 -&gt; 15

### ISSUE THREAD

**Issue by buttonpushertv** [theripper93/Combat-Booster#14]
I'm not sure what is causing this, but I'm getting a syntax error whenever I add or remove health on a token that seems to be connected to combatbooster. I'm not sure where "17 -&gt; 15" part is being generated.

Here is the full error text from this particular error:
```
foundry.js:319 Error: Syntax error, unrecognized expression: HP: 17 -&gt; 15
[Detected 1 package: combatbooster]
    at se.error (jquery.min.js:2:13639)
    at se.tokenize (jquery.min.js:2:21650)
    at se.select (jquery.min.js:2:22477)
    at Function.se [as find] (jquery.min.js:2:7116)
    at S.fn.init.find (jquery.min.js:2:25047)
    at new S.fn.init (jquery.min.js:2:25536)
    at S (jquery.min.js:2:1051)
    at CombatHud.js:14:30
    at Hooks._call (foundry.js:294:14)
    at Hooks.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10105:13)
    at foundry.js:10043:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateDocuments (foundry.js:10043:33)
    at ClientDatabaseBackend._createDocuments (foundry.js:9939:17)
    at async ChatMessage.createDocuments (document.mjs:338:21)
    at async ChatMessage.create (document.mjs:439:21)
```

And here is the current set of active modules (I know it's an insane number of mods 🤣): https://pastebin.com/adzHuj5L

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
