### ISSUE TITLE
Console Error at Startup with the SWADE system

### ISSUE THREAD

**Issue by StealthRevealed** [theripper93/Combat-Booster#25]
Hey Ripper, I want to say that this module works well for swade, and does what I need it to do, but this error keeps bugging me and I am trying to resolve it.

Do you have any idea what might be causing this? It only happens at startup from what I can tell, and it seems to be related to SWADE's unique combat tracking code to use cards instead of dice for initiative.

foundry.js:747 TypeError: Error thrown in hooked function '' for hook 'getSwadeCombatTrackerEntryContext'. Cannot read properties of undefined (reading 'CBTurnMarker')
[Detected 2 packages: combatbooster, system:swade]
    at Object.fn (main.js:73:24)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at ContextMenu.create (foundry.js:56005:13)
    at SwadeCombatTracker._contextMenu (foundry.js:75329:17)
    at SwadeCombatTracker.activateListeners (foundry.js:75121:32)
    at SwadeCombatTracker.activateListeners (SwadeCombatTracker.ts:15:11)
    at SwadeCombatTracker._render (foundry.js:5138:10)
    at async SwadeCombatTracker._render (foundry.js:60343:5)
    at async Promise.all (index 3)
    
    
![image](https://user-images.githubusercontent.com/23281162/233795895-665e054f-3929-448e-9acc-15f46a553f4b.png)

**Comment by theripper93** [comment]
fixed
