### ISSUE TITLE
FVTT v11.302 deprecation warning on scene load

### ISSUE THREAD

**Issue by epsilon7430** [theripper93/Combat-Booster#27]
Two orange level errors in sequence, to do with TurnMarker, that may be worth investigating for performance improvements mentioned. Occurs opening any scene, even those without tokens.  The errors don't appear with Combat Booster module disabled.  Thanks.

Error: InterfaceCanvasGroup.reverseMaskfilter is deprecated. Please create your own ReverseMaskFilter, or instead of attaching the filter to each of your objects extend the already masked GridLayer with a container for these objects, which is much better for performance.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:1993:19)
    at get reverseMaskfilter [as reverseMaskfilter] (foundry.js:47781:19)
    **at new TurnMarker (TurnMarker.js:6:105)**
    at Object.fn (main.js:23:5)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at Canvas.draw (foundry.js:26339:11)
    at async Scene.view (foundry.js:23455:7)
    at async Game.initializeCanvas (foundry.js:8833:20)
    at async Game.setupGame (foundry.js:8667:5)
    at async Game._initializeGameView (foundry.js:9925:5)
    at async Game.initialize (foundry.js:8588:5)

Error: InterfaceCanvasGroup.reverseMaskfilter is deprecated. Please create your own ReverseMaskFilter, or instead of attaching the filter to each of your objects extend the already masked GridLayer with a container for these objects, which is much better for performance.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:1993:19)
    at get reverseMaskfilter [as reverseMaskfilter] (foundry.js:47781:19)
    **at new TurnMarker (TurnMarker.js:6:105)**
    **at new StartTurnMarker (TurnMarker.js:164:5)**
    at Object.fn (main.js:26:7)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at Canvas.draw (foundry.js:26339:11)
    at async Scene.view (foundry.js:23455:7)

**Comment by theripper93** [comment]
This is just a warning that can be ignored, I don’t plan to “fix” it since v12 will probably get core turn markers, if not I’ll sort it by then but it will not cause any issue whatsoever before v13
